name: Feature
description: Propose a new feature
labels: [feature]
body:
  - type: textarea
    id: problem
    attributes: { label: Problem, description: What pain does this solve? }
  - type: textarea
    id: solution
    attributes: { label: Solution outline, description: Key user flows / AC }
  - type: input
    id: metric
    attributes: { label: Success metric }
