name: Spike
description: Timeboxed investigation
labels: [spike]
body:
  - type: textarea
    id: question
    attributes: { label: Question to answer }
  - type: input
    id: timebox
    attributes: { label: Timebox (e.g., 6h) }
  - type: textarea
    id: acceptance
    attributes: { label: Acceptance (decision memo, metrics, recommendation) }
